# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(verbose_name='OAuth2 redirect URL')),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('auth_url', models.URLField(verbose_name='OAuth2 auth URL')),
                ('token_url', models.URLField(verbose_name='OAuth2 token URL')),
                ('rest_url', models.URLField(verbose_name='API base URL')),
                ('access_expiry', models.CharField(default='', max_length=255)),
                ('access_token', models.TextField(default='')),
                ('refresh_token', models.TextField(default='')),
                ('code', models.TextField(default='')),
                ('division', models.TextField()),
            ],
        ),
    ]
