# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import exact.models


class Migration(migrations.Migration):

    dependencies = [
        ('exact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('Accounts', 'Accounts'), ('BankAccounts', 'Bank Accounts'), ('Contacts', 'Contacts'), ('CostTransactions', 'CostTransactions'), ('DocumentAttachments', 'Document Attachments'), ('Documents', 'Documents'), ('FinancialTransactions', 'FinancialTransactions'), ('GoodsDeliveries', 'GoodsDeliveries'), ('Items', 'Items'), ('ProjectPlanning', 'ProjectPlanning'), ('PurchaseOrders', 'PurchaseOrders'), ('Quotations', 'Quotations'), ('SalesInvoices', 'SalesInvoices'), ('SalesOrders', 'SalesOrders'), ('StockPositions', 'StockPositions'), ('TimeTransactions', 'TimeTransactions')], max_length=255)),
                ('callback', models.URLField(default=exact.models._default_callback_url, help_text='Webhook callback', verbose_name='Callback')),
                ('guid', models.UUIDField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='session',
            name='access_expiry',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='session',
            name='access_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='session',
            name='code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='session',
            name='refresh_token',
            field=models.TextField(blank=True, default=''),
        ),
    ]
